name: CI

on: [pull_request]

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  basic:
    name: Run tests on PHP ${{ matrix.php_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['8.0', '8.1', '8.2']
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Deps
        run: composer install --no-interaction

      - name: Quality
        if: matrix.php-versions == '8.0'
        run: vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php -v --dry-run --stop-on-violation

      - name: Test
        run: vendor/bin/phpunit
